name: Déploiement sur VM locale

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer la clé privée (ed25519)
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Vérifier que la clé est valide pour ssh
        run: |
          set -e
          head -1 ~/.ssh/id_ed25519
          tail -1 ~/.ssh/id_ed25519
          echo "--- fingerprint ---"
          ssh-keygen -lf ~/.ssh/id_ed25519
          echo "--- public dérivée ---"
          ssh-keygen -y -f ~/.ssh/id_ed25519 | head -c 80; echo
          # si cette commande échoue => clé invalide (secret mal collé)

      - name: Pré-enregistrer l'hôte
        run: |
          ssh-keyscan -H "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Test SSH non interactif
        run: |
          ssh -o BatchMode=yes -o StrictHostKeyChecking=yes -o ConnectTimeout=15 \
              -i ~/.ssh/id_ed25519 "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}" \
              "echo 'Connexion OK depuis GitHub Actions'"
