name: Déploiement sur VM locale

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer la clé privée (CI)
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          # écrit la clé sans \r Windows
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/ci_deploy_key
          chmod 600 ~/.ssh/ci_deploy_key
          ssh-keyscan -H "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Test SSH non interactif (debug)
        run: |
          ssh -vvv \
            -o AddressFamily=inet \
            -o BatchMode=yes \
            -o StrictHostKeyChecking=yes \
            -o ConnectTimeout=15 \
            -i ~/.ssh/ci_deploy_key \
            "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}" \
            "echo 'Connexion OK depuis GitHub Actions'"
