name: Déploiement Automatisé

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Déploiement sur VM locale
    runs-on: self-hosted

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Créer le fichier de clé privée
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Connexion SSH et déploiement
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key deployer@192.168.248.147 << 'EOF'
            mkdir -p ~/deploiement
            exit
          EOF

      - name: Copier le fichier index.html sur la VM
        run: |
          scp -o StrictHostKeyChecking=no -i private_key ./index.html deployer@192.168.248.147:~/deploiement/

