name: Déploiement sur VM locale

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Déploiement sur VM locale
    runs-on: self-hosted

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Créer le fichier de clé privée
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Connexion SSH et déploiement
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa deployer@192.168.248.147 "echo 'Connexion OK depuis GitHub Actions'"
